export const QueryPackingIn = `SELECT SA.PACK_BRCD_LINE SLINE, SC.LINE_PREF, SC.LINE_UNIT, 
SC.LINE_NAME_SPV, SC.LINE_DESC, SA.PACK_BRCD_PART SPART, SB.PART_NAME, SB.PART_FCH_BUYER, SB.PART_FCH_ACTUAL,
 SB.PART_UNIT,
SUM(QTY_PLN) QTY_PL, SUM(QTY_ACT) QTY_ACT, SUM(QTY_PR) QTY_PR, SUM(QTY_IN) QTY_IN,
SUM(QTY_IN_07) QTY_IN_07, SUM(QTY_IN_08) QTY_IN_08, SUM(QTY_IN_09) QTY_IN_09,
SUM(QTY_IN_10) QTY_IN_10, SUM(QTY_IN_11) QTY_IN_11, SUM(QTY_IN_12) QTY_IN_12,
SUM(QTY_IN_13) QTY_IN_13, SUM(QTY_IN_14) QTY_IN_14, SUM(QTY_IN_15) QTY_IN_15,
SUM(QTY_IN_16) QTY_IN_16, SUM(QTY_IN_17) QTY_IN_17, SUM(QTY_IN_18) QTY_IN_18,
SUM(QTY_IN_19) QTY_IN_19, SUM(QTY_IN_20) QTY_IN_20, SUM(QTY_IN_21) QTY_IN_21
FROM (
SELECT
A.SCAN_DATE, B.PACK_BRCD_LINE, B.PACK_BRCD_PART, 0 QTY_PLN, 0 QTY_ACT, 0 QTY_PR,
  SUM(B.PACK_BRCD_QTY) QTY_IN,
  (CASE WHEN (HOUR(A.SCAN_TIME) = 7) THEN SUM(B.PACK_BRCD_QTY) ELSE 0 END) AS QTY_IN_07,
  (CASE WHEN (HOUR(A.SCAN_TIME) = 8) THEN SUM(B.PACK_BRCD_QTY) ELSE 0 END) AS QTY_IN_08,
  (CASE WHEN (HOUR(A.SCAN_TIME) = 9) THEN SUM(B.PACK_BRCD_QTY) ELSE 0 END) AS QTY_IN_09,
  (CASE WHEN (HOUR(A.SCAN_TIME) = 10) THEN SUM(B.PACK_BRCD_QTY) ELSE 0 END) AS QTY_IN_10,
  (CASE WHEN (HOUR(A.SCAN_TIME) = 11) THEN SUM(B.PACK_BRCD_QTY) ELSE 0 END) AS QTY_IN_11,
  (CASE WHEN (HOUR(A.SCAN_TIME) = 12) THEN SUM(B.PACK_BRCD_QTY) ELSE 0 END) AS QTY_IN_12,
  (CASE WHEN (HOUR(A.SCAN_TIME) = 13) THEN SUM(B.PACK_BRCD_QTY) ELSE 0 END) AS QTY_IN_13,
  (CASE WHEN (HOUR(A.SCAN_TIME) = 14) THEN SUM(B.PACK_BRCD_QTY) ELSE 0 END) AS QTY_IN_14,
  (CASE WHEN (HOUR(A.SCAN_TIME) = 15) THEN SUM(B.PACK_BRCD_QTY) ELSE 0 END) AS QTY_IN_15,
  (CASE WHEN (HOUR(A.SCAN_TIME) = 16) THEN SUM(B.PACK_BRCD_QTY) ELSE 0 END) AS QTY_IN_16,
  (CASE WHEN (HOUR(A.SCAN_TIME) = 17) THEN SUM(B.PACK_BRCD_QTY) ELSE 0 END) AS QTY_IN_17,
  (CASE WHEN (HOUR(A.SCAN_TIME) = 18) THEN SUM(B.PACK_BRCD_QTY) ELSE 0 END) AS QTY_IN_18,
  (CASE WHEN (HOUR(A.SCAN_TIME) = 19) THEN SUM(B.PACK_BRCD_QTY) ELSE 0 END) AS QTY_IN_19,
  (CASE WHEN (HOUR(A.SCAN_TIME) = 20) THEN SUM(B.PACK_BRCD_QTY) ELSE 0 END) AS QTY_IN_20,
  (CASE WHEN (HOUR(A.SCAN_TIME) = 21) THEN SUM(B.PACK_BRCD_QTY) ELSE 0 END) AS QTY_IN_21
FROM pack_scan A
LEFT JOIN pack_brcd B ON A.SCAN_ID = B.PACK_BRCD_NUM
WHERE B.PACK_BRCD_DATE =  :date 
  AND A.SCAN_FLAG ='I' AND B.PACK_BRCD_FLAG <> 'A'
GROUP BY B.PACK_BRCD_DATE, HOUR(A.SCAN_TIME), B.PACK_BRCD_LINE, B.PACK_BRCD_PART
UNION ALL
SELECT
  A0.PLAN_PROD_DATE, A0.PLAN_PROD_LINE_CODE, A0.PLAN_PROD_PART,
  SUM(A0.QTY_PLN) QTY_PLN, SUM(QTY_ACT) QTY_ACT,
  SUM(A0.QTY_PR),
  0 QTY_IN,
  0 QTY_IN_07, 0 QTY_IN_08, 0 QTY_IN_09,
  0 QTY_IN_10, 0 QTY_IN_11, 0 QTY_IN_12,
  0 QTY_IN_13, 0 QTY_IN_14, 0 QTY_IN_15,
  0 QTY_IN_16, 0 QTY_IN_17, 0 AS QTY_IN_18,
  0 QTY_IN_19, 0 QTY_IN_20, 0 QTY_IN_21
FROM (
   SELECT
   A0.PLAN_PROD_DATE, A0.PLAN_PROD_LINE_CODE, A0.PLAN_PROD_PART,
   A0.PLAN_PROD_QTY QTY_PLN, IFNULL(ROUND((A0.PLAN_PROD_QTY / A0.PLAN_PROD_OPT) * B.OUT_PROD_GOOD_AHC),0) QTY_ACT,
   IFNULL((
    SELECT SUM(XN.OUT_PROD_QTY) FROM output_prod_good XN WHERE IFNULL(XN.OUT_PROD_FLAG_DEL,'') <> 'D' AND XN.OUT_PLAN_ID =
    REPLACE(CONCAT(CAST(A0.PLAN_PROD_DATE AS CHAR), CAST(A0.PLAN_PROD_LINE_CODE AS CHAR),
    CAST(A0.PLAN_PROD_PART AS CHAR),
    CAST(A0.PLAN_PROD_FLAG AS CHAR), CAST(A0.PLAN_PROD_GROUP AS CHAR)),'-','') AND
    XN.OUT_PROD_DATE =  :date 
  ),0) QTY_PR
   FROM plan_prod_daily A0 LEFT JOIN output_prod_good_hc B ON B.PLAN_ID =
        REPLACE(CONCAT(CAST(A0.PLAN_PROD_DATE AS CHAR), CAST(A0.PLAN_PROD_LINE_CODE AS CHAR),
        CAST(A0.PLAN_PROD_PART AS CHAR),
        CAST(A0.PLAN_PROD_FLAG AS CHAR), CAST(A0.PLAN_PROD_GROUP AS CHAR)),'-','')
   WHERE A0.PLAN_PROD_DATE =  :date 
) A0
GROUP BY A0.PLAN_PROD_DATE, A0.PLAN_PROD_LINE_CODE, A0.PLAN_PROD_PART
) SA
LEFT JOIN toy_part SB ON SA.PACK_BRCD_PART = SB.PART_NUM
LEFT JOIN line SC ON SA.PACK_BRCD_LINE = SC.LINE_CODE
WHERE 1=1  AND SC.LINE_PREF LIKE :unit
GROUP BY SA.PACK_BRCD_LINE, SC.LINE_DESC, SA.PACK_BRCD_PART, SB.PART_NAME, SB.PART_UNIT
ORDER BY SC.LINE_PREF, SC.LINE_ORDR, SA.PACK_BRCD_PART`;
