export const QuerySewDailyRep = `SELECT 
NB.OUT_PLAN_ID, NB.PLAN_PROD_DATE, NB.LINE_PREF, NB.LINE_ORDR, NB.LINE_CODE, 
NB.LINE_DESC, NB.LINE_NAME_SPV, NB.FCH, NB.OT_FLAG, NB.UNIT, NB.PLAN_PROD_CONSLD, NB.PARTN, NE.PART_NAME, NB.PROD_GROUP,
PLAN_HC, ACT_HC, NL_WH, NL_TARGET, ACT_TARGET, ACT_TARGET_JAM,
PROD_TIME_07, PROD_TIME_08, PROD_TIME_09,
PROD_TIME_10, PROD_TIME_11, PROD_TIME_12,
PROD_TIME_13, PROD_TIME_14, PROD_TIME_15,
PROD_TIME_16, PROD_TIME_17, PROD_TIME_18,
PROD_TIME_19, PROD_TIME_20, PROD_TIME_21,
PROD_TIME_TOTAL,
NF.DEF_QTY,
NG.REJ_QTY,
ND.REMARK
FROM (	
	SELECT PLAN_PROD_DATE, OUT_PLAN_ID, LINE_CODE, LINE_DESC, LINE_NAME_SPV, PARTN, FCH, OT_FLAG, UNIT, PLAN_PROD_CONSLD, PROD_GROUP,
	PLAN_HC, ACT_HC, NL_WH, NL_TARGET, OT_WH, OT_TARGET, OT_ACT_TARGET, OT_ACT_TARGET_JAM, 
	ACT_TARGET, ACT_TARGET_JAM, LINE_PREF, LINE_ORDR,
	PLAN_PROD_ORDR,
	SUM(PROD_TIME_07) PROD_TIME_07,SUM(PROD_TIME_08) PROD_TIME_08,SUM(PROD_TIME_09) PROD_TIME_09,
	SUM(PROD_TIME_10) PROD_TIME_10,SUM(PROD_TIME_11) PROD_TIME_11,SUM(PROD_TIME_12) PROD_TIME_12,
	SUM(PROD_TIME_13) PROD_TIME_13,SUM(PROD_TIME_14) PROD_TIME_14,SUM(PROD_TIME_15) PROD_TIME_15,
	SUM(PROD_TIME_16) PROD_TIME_16,SUM(PROD_TIME_17) PROD_TIME_17,SUM(PROD_TIME_18) PROD_TIME_18,
	SUM(PROD_TIME_19) PROD_TIME_19,	SUM(PROD_TIME_20) PROD_TIME_20,SUM(PROD_TIME_21) PROD_TIME_21, 
	SUM(PROD_TIME_TOTAL) PROD_TIME_TOTAL,
	(SUM(PROD_TIME_TOTAL)*FCH)/1000 EH, 
	(ACT_TARGET*FCH)/1000 TARGET_EH, 
	ACT_HC*NL_WH PLAN_AH
	FROM (
		SELECT B.OUT_PLAN_ID,
			B.PLAN_PROD_DATE,
			B.PLAN_PROD_LINE_CODE LINE_CODE,
			C.LINE_DESC LINE_DESC,
			C.LINE_UNIT UNIT,
			C.LINE_NAME_SPV,
			B.PLAN_PROD_CONSLD,
			B.PLAN_PROD_PART PARTN, 
			B.PLAN_PROD_FCH FCH,
			B.PLAN_PROD_GROUP PROD_GROUP,
			B.PLAN_PROD_OPT PLAN_HC,
			E.OUT_PROD_GOOD_AHC ACT_HC,
			B.PLAN_PROD_FLAG OT_FLAG,
			B.PLAN_PROD_WH NL_WH,
			B.PLAN_PROD_QTY NL_TARGET,
			C.LINE_PREF, 
			0 OT_WH,
			0 OT_TARGET,
			0 OT_ACT_TARGET,
			0 OT_ACT_TARGET_JAM,
			B.PLAN_PROD_ORDR,LINE_ORDR,
			ROUND((IFNULL(B.PLAN_PROD_QTY,0) / IFNULL(B.PLAN_PROD_OPT,0)) * IFNULL(E.OUT_PROD_GOOD_AHC,0)) ACT_TARGET,
			ROUND((IFNULL(B.PLAN_PROD_QTY,0) / IFNULL(B.PLAN_PROD_OPT,0)) * IFNULL(E.OUT_PROD_GOOD_AHC,0) / B.PLAN_PROD_WH) ACT_TARGET_JAM,
			CASE WHEN HOUR(A.OUT_PROD_TIME) = 7 THEN SUM(A.OUT_PROD_QTY) END PROD_TIME_07,
			CASE WHEN HOUR(A.OUT_PROD_TIME) = 8 THEN SUM(A.OUT_PROD_QTY) END PROD_TIME_08,
			CASE WHEN HOUR(A.OUT_PROD_TIME) = 9 THEN SUM(A.OUT_PROD_QTY) END PROD_TIME_09,
			CASE WHEN HOUR(A.OUT_PROD_TIME) = 10 THEN SUM(A.OUT_PROD_QTY) END PROD_TIME_10,
			CASE WHEN HOUR(A.OUT_PROD_TIME) = 11 THEN SUM(A.OUT_PROD_QTY) END PROD_TIME_11,
			CASE WHEN HOUR(A.OUT_PROD_TIME) = 12 THEN SUM(A.OUT_PROD_QTY) END PROD_TIME_12,
			CASE WHEN HOUR(A.OUT_PROD_TIME) = 13 THEN SUM(A.OUT_PROD_QTY) END PROD_TIME_13,
			CASE WHEN HOUR(A.OUT_PROD_TIME) = 14 THEN SUM(A.OUT_PROD_QTY) END PROD_TIME_14,
			CASE WHEN HOUR(A.OUT_PROD_TIME) = 15 THEN SUM(A.OUT_PROD_QTY) END PROD_TIME_15,
			CASE WHEN HOUR(A.OUT_PROD_TIME) = 16 THEN SUM(A.OUT_PROD_QTY) END PROD_TIME_16,
			CASE WHEN HOUR(A.OUT_PROD_TIME) = 17 THEN SUM(A.OUT_PROD_QTY) END PROD_TIME_17,
			CASE WHEN HOUR(A.OUT_PROD_TIME) = 18 THEN SUM(A.OUT_PROD_QTY) END PROD_TIME_18,
			CASE WHEN HOUR(A.OUT_PROD_TIME) = 19 THEN SUM(A.OUT_PROD_QTY) END PROD_TIME_19,
			CASE WHEN HOUR(A.OUT_PROD_TIME) = 20 THEN SUM(A.OUT_PROD_QTY) END PROD_TIME_20,
			CASE WHEN HOUR(A.OUT_PROD_TIME) = 21 THEN SUM(A.OUT_PROD_QTY) END PROD_TIME_21,
			SUM(A.OUT_PROD_QTY) PROD_TIME_TOTAL 
		FROM plan_prod_daily_view_board B 
		LEFT JOIN line C ON B.PLAN_PROD_LINE_CODE = C.LINE_CODE
		LEFT JOIN output_prod_good A ON A.OUT_PLAN_ID = B.OUT_PLAN_ID AND IFNULL(A.OUT_PROD_FLAG_DEL, TRUE) = TRUE
		LEFT JOIN output_prod_good_hc E ON E.PLAN_ID = B.OUT_PLAN_ID
		WHERE B.PLAN_PROD_DATE = :date AND C.LINE_PREF LIKE  :unit 
		GROUP BY	
			B.OUT_PLAN_ID,
			A.OUT_PROD_DATE,
			A.OUT_PROD_TIME, 
			B.PLAN_PROD_LINE_CODE, 
			B.PLAN_PROD_DATE,
			C.LINE_UNIT,
			C.LINE_DESC,
			A.OUT_PROD_PART, 
			A.OUT_PROD_ACT_HC, 
			B.PLAN_PROD_QTY,
			C.LINE_PREF, 
			C.LINE_UNIT,
			LINE_ORDR,
			PROD_GROUP
	) NA	
	GROUP BY 
	OUT_PLAN_ID, LINE_CODE, LINE_DESC, PARTN, FCH, OT_FLAG, UNIT, PLAN_PROD_CONSLD, PROD_GROUP,
	PLAN_HC, ACT_HC, NL_WH, NL_TARGET, OT_WH, OT_TARGET, OT_ACT_TARGET, OT_ACT_TARGET_JAM, 
	ACT_TARGET, ACT_TARGET_JAM, LINE_PREF, LINE_ORDR,
	PLAN_PROD_ORDR
) NB LEFT JOIN plan_prod_time_view NC ON NB.OUT_PLAN_ID = NC.OUT_PLAN_ID
	LEFT JOIN prod_remark ND ON NB.OUT_PLAN_ID = ND.PLAN_ID
	LEFT JOIN toy_part NE ON NB.PARTN = NE.PART_NUM
	LEFT JOIN (
		SELECT XZ.OUT_PLAN_ID, SUM(XZ.OUT_DEF_QTY) DEF_QTY
		FROM output_prod_defect XZ WHERE IFNULL(XZ.OUT_PROD_FLAG_DEL, '') <> 'D' AND XZ.OUT_DEF_CODE <> 8 
		AND XZ.OUT_DEF_DATE = :date
		GROUP BY XZ.OUT_PLAN_ID
	) NF ON NB.OUT_PLAN_ID = NF.OUT_PLAN_ID
	LEFT JOIN (
	SELECT XZ.OUT_PLAN_ID, SUM(XZ.OUT_REJ_QTY) REJ_QTY
		FROM output_prod_reject XZ WHERE IFNULL(XZ.OUT_PROD_FLAG_DEL, '') <> 'D'
		AND XZ.OUT_REJ_DATE = :date 
		GROUP BY XZ.OUT_PLAN_ID
	) NG ON NB.OUT_PLAN_ID = NG.OUT_PLAN_ID
	LEFT JOIN (
		SELECT XY.PLAN_PROD_GROUP, XY.PLAN_PROD_LINE_CODE, XY.PLAN_PROD_FLAG, XY.PLAN_PROD_DATE,  XY.PLAN_PROD_CONSLD, COUNT(*) COUNT_GROUP
		FROM plan_prod_daily XY 
		WHERE XY.PLAN_PROD_DATE = :date
		GROUP BY XY.PLAN_PROD_GROUP, XY.PLAN_PROD_LINE_CODE, XY.PLAN_PROD_FLAG, XY.PLAN_PROD_DATE, XY.PLAN_PROD_CONSLD
	) NH ON NB.PROD_GROUP = NH.PLAN_PROD_GROUP AND NB.LINE_CODE = NH.PLAN_PROD_LINE_CODE AND NB.PLAN_PROD_DATE = NH.PLAN_PROD_DATE AND NH.PLAN_PROD_FLAG = NB.OT_FLAG
		AND NH.PLAN_PROD_CONSLD = NB.PLAN_PROD_CONSLD
ORDER BY
	NB.LINE_PREF,
	NB.LINE_ORDR,
	NB.PROD_GROUP,
	NB.PLAN_PROD_ORDR,
	NB.OT_FLAG`;

export const QueryListLineSew = `SELECT DISTINCT C.LINE_UNIT, B.PLAN_PROD_LINE_CODE LINE_CODE, C.LINE_DESC, C.LINE_NAME_SPV FROM plan_prod_daily_view_board B 
LEFT JOIN line C ON B.PLAN_PROD_LINE_CODE = C.LINE_CODE
WHERE B.PLAN_PROD_DATE =:date AND C.LINE_PREF LIKE :unit
ORDER BY C.LINE_UNIT, C.LINE_ORDR`;

export const QueryListUnit = `SELECT DISTINCT C.LINE_PREF, C.LINE_UNIT FROM plan_prod_daily_view_board B 
LEFT JOIN line C ON B.PLAN_PROD_LINE_CODE = C.LINE_CODE
WHERE B.PLAN_PROD_DATE =:date AND C.LINE_PREF LIKE :unit
ORDER BY C.LINE_ORDR`;

// QUERY REPORT SUMMARY

export const QuerySummaryReport = `SELECT a.OUT_PLAN_ID, a.PLAN_PROD_DATE, i.LINE_PREF, i.LINE_ORDR, i.LINE_CODE, i.LINE_DESC,  i.LINE_NAME_SPV,	
a.PLAN_PROD_FCH FCH, a.PLAN_PROD_FLAG OT_FLAG, i.LINE_UNIT UNIT, a.PLAN_PROD_CONSLD,  
a.PLAN_PROD_PART PARTN, j.PART_NAME, a.PLAN_PROD_GROUP PROD_GROUP, a.PLAN_PROD_OPT PLAN_HC, 
b.OUT_PROD_GOOD_AHC ACT_HC, a.PLAN_PROD_WH NL_WH, a.PLAN_PROD_QTY NL_TARGET, 
ROUND((IFNULL(a.PLAN_PROD_QTY,0) / IFNULL(a.PLAN_PROD_OPT,0)) * IFNULL(b.OUT_PROD_GOOD_AHC,0)) ACT_TARGET,
ROUND(((IFNULL(a.PLAN_PROD_QTY,0) / IFNULL(a.PLAN_PROD_OPT,0)) * IFNULL(b.OUT_PROD_GOOD_AHC,0)) / a.PLAN_PROD_WH ) ACT_TARGET_JAM, 
c.OUT_PROD_QTY PROD_TIME_TOTAL, d.FIRST_TIME, d.LAST_TIME,
d.FIRST_TIME_INPUT, d.LAST_TIME_INPUT, 
count_actual_wh(d.FIRST_TIME_INPUT, d.LAST_TIME_INPUT, a.PLAN_PROD_DATE) ACT_HOUR, 
(((IFNULL(a.PLAN_PROD_QTY,0) / IFNULL(a.PLAN_PROD_OPT,0)) * IFNULL(b.OUT_PROD_GOOD_AHC,0)) * a.PLAN_PROD_FCH) / 1000 TARGET_EH, 
(c.OUT_PROD_QTY * a.PLAN_PROD_FCH) / 1000 EH, 
(b.OUT_PROD_GOOD_AHC * a.PLAN_PROD_WH) PLAN_AH, 
b.OUT_PROD_GOOD_AHC * count_actual_wh(d.FIRST_TIME_INPUT, d.LAST_TIME_INPUT, a.PLAN_PROD_DATE) ACTUAL_AH, 
((((IFNULL(a.PLAN_PROD_QTY,0) / IFNULL(a.PLAN_PROD_OPT,0)) * IFNULL(b.OUT_PROD_GOOD_AHC,0)) * a.PLAN_PROD_FCH) / 1000) / (b.OUT_PROD_GOOD_AHC * a.PLAN_PROD_WH)  TARGET_EFF, 
((c.OUT_PROD_QTY * a.PLAN_PROD_FCH) / 1000) / (b.OUT_PROD_GOOD_AHC * count_actual_wh(d.FIRST_TIME_INPUT, d.LAST_TIME_INPUT, a.PLAN_PROD_DATE)) EFF,
e.COUNT_GROUP, f.DEF_QTY, g.REJ_QTY, h.REMARK
FROM plan_prod_daily_view_board a 
LEFT JOIN output_prod_good_hc b ON a.OUT_PLAN_ID = b.PLAN_ID
LEFT JOIN output_prod_good_daily c ON a.OUT_PLAN_ID = c.OUT_PLAN_ID
LEFT JOIN plan_prod_time_view d ON a.OUT_PLAN_ID  = d.OUT_PLAN_ID
LEFT JOIN (
	SELECT e.PLAN_PROD_GROUP, e.PLAN_PROD_LINE_CODE, e.PLAN_PROD_FLAG, e.PLAN_PROD_DATE,  e.PLAN_PROD_CONSLD, COUNT(*) COUNT_GROUP
	FROM plan_prod_daily e 
	WHERE e.PLAN_PROD_DATE =  :date
	GROUP BY e.PLAN_PROD_GROUP, e.PLAN_PROD_LINE_CODE, e.PLAN_PROD_FLAG, e.PLAN_PROD_DATE, e.PLAN_PROD_CONSLD
) e ON a.PLAN_PROD_GROUP = e.PLAN_PROD_GROUP AND a.PLAN_PROD_LINE_CODE = e.PLAN_PROD_LINE_CODE AND a.PLAN_PROD_DATE = e.PLAN_PROD_DATE 
	AND a.PLAN_PROD_FLAG = e.PLAN_PROD_FLAG AND a.PLAN_PROD_CONSLD = e.PLAN_PROD_CONSLD
LEFT JOIN (
	SELECT XZ.OUT_PLAN_ID, SUM(XZ.OUT_DEF_QTY) DEF_QTY
	FROM output_prod_defect_daily XZ WHERE XZ.OUT_DEF_CODE <> 8 AND XZ.OUT_DEF_DATE = :date
	GROUP BY XZ.OUT_PLAN_ID
) f ON a.OUT_PLAN_ID = f.OUT_PLAN_ID
LEFT JOIN (
	SELECT XZ.OUT_PLAN_ID, SUM(XZ.OUT_REJ_QTY) REJ_QTY
	FROM output_prod_reject XZ WHERE IFNULL(XZ.OUT_PROD_FLAG_DEL, '') <> 'D'
	AND XZ.OUT_REJ_DATE = :date 
	GROUP BY XZ.OUT_PLAN_ID
) g ON a.OUT_PLAN_ID = g.OUT_PLAN_ID  
LEFT JOIN prod_remark h ON a.OUT_PLAN_ID = h.PLAN_ID
LEFT JOIN line i ON a.PLAN_PROD_LINE_CODE = i.LINE_CODE
LEFT JOIN toy_part j ON a.PLAN_PROD_PART = j.PART_NUM 
WHERE a.PLAN_PROD_DATE = :date AND i.LINE_PREF LIKE :unit
ORDER BY  i.LINE_PREF, i.LINE_ORDR,
a.PLAN_PROD_GROUP,a.PLAN_PROD_ORDR, a.PLAN_PROD_FLAG`;
