import { QueryTypes } from 'sequelize';

import db from '../../config/database.js';
export const QueryFindNormal = `SELECT REPLACE(CONCAT(CAST(NA.PLAN_PROD_DATE AS CHAR),
CAST(NA.PLAN_PROD_LINE_CODE AS CHAR),
CAST(NA.PLAN_PROD_PART AS CHAR),
CAST(NA.PLAN_PROD_FLAG AS CHAR),
CAST(NA.PLAN_PROD_GROUP AS CHAR)),'-','') PLAN_ID_NORMAL, 
REPLACE(CONCAT(CAST(NB.PLAN_PROD_DATE AS CHAR),
CAST(NB.PLAN_PROD_LINE_CODE AS CHAR),
CAST(NB.PLAN_PROD_PART AS CHAR),
CAST(NB.PLAN_PROD_FLAG AS CHAR),
CAST(NB.PLAN_PROD_GROUP AS CHAR)),'-','') PLAN_ID_OT, 
N.PLAN_PROD_WEEK, 
N.PLAN_PROD_DATE, 
N.PLAN_PROD_CONSLD,
N.PLAN_PROD_LINE_CODE,
LINE_UNIT, 
LINE_NAME_SPV,
LINE_DESC,
LINE_ORDR,
LINE_PREF,
N.PLAN_PROD_PART,
PART_NAME,
PART_TOY_SN,
N.PLAN_PROD_OPT,
N0.PART_FCH_BUYER PLAN_PROD_FCH,
N.PLAN_PROD_GROUP , 
NA.PLAN_PROD_EFF EFF_NORMAL,
NA.PLAN_PROD_WH WH_NORMAL, 
NA.PLAN_PROD_QTY QTY_NORMAL,
NB.PLAN_PROD_EFF EFF_OT, 
NC.OUT_PROD_GOOD_AHC A_HC, 
ND.OUT_PROD_GOOD_AHC A_HC_OT,
NB.PLAN_PROD_WH WH_OT, 
NB.PLAN_PROD_QTY QTY_OT 

FROM (
	SELECT DISTINCT 
	A.PLAN_PROD_WEEK, 
	A.PLAN_PROD_DATE, 
	A.PLAN_PROD_LINE_CODE,
	A.PLAN_PROD_PART, 		 
 	A.PLAN_PROD_CONSLD,
	A.PLAN_PROD_FCH,
	A.PLAN_PROD_OPT,
	#A.PLAN_PROD_ACT_HC A_HC,
	A.PLAN_PROD_GROUP 
	#A.PLAN_PROD_REF,
	FROM plan_prod_daily A WHERE A.PLAN_PROD_DATE = :date
) N 
LEFT JOIN plan_prod_daily NA ON NA.PLAN_PROD_WEEK = N.PLAN_PROD_WEEK AND
NA.PLAN_PROD_DATE = N.PLAN_PROD_DATE AND 
NA.PLAN_PROD_PART = N.PLAN_PROD_PART AND 
NA.PLAN_PROD_LINE_CODE = N.PLAN_PROD_LINE_CODE AND
NA.PLAN_PROD_FLAG = 'N' AND 
NA.PLAN_PROD_GROUP = N.PLAN_PROD_GROUP
LEFT JOIN plan_prod_daily NB ON NB.PLAN_PROD_WEEK = N.PLAN_PROD_WEEK AND 
NB.PLAN_PROD_DATE = N.PLAN_PROD_DATE AND 
NB.PLAN_PROD_PART = N.PLAN_PROD_PART AND 
NB.PLAN_PROD_LINE_CODE = N.PLAN_PROD_LINE_CODE AND
NB.PLAN_PROD_FLAG = 'O' AND
NB.PLAN_PROD_GROUP = N.PLAN_PROD_GROUP  
LEFT JOIN output_prod_good_hc NC ON REPLACE(CONCAT(CAST(NA.PLAN_PROD_DATE AS CHAR),
CAST(NA.PLAN_PROD_LINE_CODE AS CHAR),
CAST(NA.PLAN_PROD_PART AS CHAR),
CAST(NA.PLAN_PROD_FLAG AS CHAR),
CAST(NA.PLAN_PROD_GROUP AS CHAR)),'-','') = NC.PLAN_ID
LEFT JOIN output_prod_good_hc ND ON REPLACE(CONCAT(CAST(NB.PLAN_PROD_DATE AS CHAR),
CAST(NB.PLAN_PROD_LINE_CODE AS CHAR),
CAST(NB.PLAN_PROD_PART AS CHAR),
CAST(NB.PLAN_PROD_FLAG AS CHAR),
CAST(NB.PLAN_PROD_GROUP AS CHAR)),'-','') = ND.PLAN_ID
LEFT JOIN toy_part N0 ON N.PLAN_PROD_PART = PART_NUM
LEFT JOIN line N1 ON N.PLAN_PROD_LINE_CODE= LINE_CODE 
WHERE REPLACE(CONCAT(CAST(NA.PLAN_PROD_DATE AS CHAR),
CAST(NA.PLAN_PROD_LINE_CODE AS CHAR),
CAST(NA.PLAN_PROD_PART AS CHAR),
CAST(NA.PLAN_PROD_FLAG AS CHAR),
CAST(NA.PLAN_PROD_GROUP AS CHAR)),'-','') = :idnormal
ORDER BY  LINE_PREF, LINE_ORDR, N.PLAN_PROD_LINE_CODE, LINE_UNIT,  N.PLAN_PROD_GROUP`;

export const QueryFindOt = `SELECT REPLACE(CONCAT(CAST(NA.PLAN_PROD_DATE AS CHAR),
CAST(NA.PLAN_PROD_LINE_CODE AS CHAR),
CAST(NA.PLAN_PROD_PART AS CHAR),
CAST(NA.PLAN_PROD_FLAG AS CHAR),
CAST(NA.PLAN_PROD_GROUP AS CHAR)),'-','') PLAN_ID_NORMAL, 
REPLACE(CONCAT(CAST(NB.PLAN_PROD_DATE AS CHAR),
CAST(NB.PLAN_PROD_LINE_CODE AS CHAR),
CAST(NB.PLAN_PROD_PART AS CHAR),
CAST(NB.PLAN_PROD_FLAG AS CHAR),
CAST(NB.PLAN_PROD_GROUP AS CHAR)),'-','') PLAN_ID_OT, 
N.PLAN_PROD_WEEK, 
N.PLAN_PROD_DATE, 
N.PLAN_PROD_CONSLD,
N.PLAN_PROD_LINE_CODE,
LINE_UNIT, 
LINE_NAME_SPV,
LINE_DESC,
LINE_ORDR,
LINE_PREF,
N.PLAN_PROD_PART,
PART_NAME,
PART_TOY_SN,
N.PLAN_PROD_OPT,
N0.PART_FCH_BUYER PLAN_PROD_FCH,
N.PLAN_PROD_GROUP , 
NA.PLAN_PROD_EFF EFF_NORMAL,
NA.PLAN_PROD_WH WH_NORMAL, 
NA.PLAN_PROD_QTY QTY_NORMAL,
NB.PLAN_PROD_EFF EFF_OT, 
NC.OUT_PROD_GOOD_AHC A_HC, 
ND.OUT_PROD_GOOD_AHC A_HC_OT,
NB.PLAN_PROD_WH WH_OT, 
NB.PLAN_PROD_QTY QTY_OT 

FROM (
	SELECT DISTINCT 
	A.PLAN_PROD_WEEK, 
	A.PLAN_PROD_DATE, 
	A.PLAN_PROD_LINE_CODE,
	A.PLAN_PROD_PART, 		 
 	A.PLAN_PROD_CONSLD,
	A.PLAN_PROD_FCH,
	A.PLAN_PROD_OPT,
	#A.PLAN_PROD_ACT_HC A_HC,
	A.PLAN_PROD_GROUP 
	#A.PLAN_PROD_REF,
	FROM plan_prod_daily A WHERE A.PLAN_PROD_DATE = :date
) N 
LEFT JOIN plan_prod_daily NA ON NA.PLAN_PROD_WEEK = N.PLAN_PROD_WEEK AND
NA.PLAN_PROD_DATE = N.PLAN_PROD_DATE AND 
NA.PLAN_PROD_PART = N.PLAN_PROD_PART AND 
NA.PLAN_PROD_LINE_CODE = N.PLAN_PROD_LINE_CODE AND
NA.PLAN_PROD_FLAG = 'N' AND 
NA.PLAN_PROD_GROUP = N.PLAN_PROD_GROUP
LEFT JOIN plan_prod_daily NB ON NB.PLAN_PROD_WEEK = N.PLAN_PROD_WEEK AND 
NB.PLAN_PROD_DATE = N.PLAN_PROD_DATE AND 
NB.PLAN_PROD_PART = N.PLAN_PROD_PART AND 
NB.PLAN_PROD_LINE_CODE = N.PLAN_PROD_LINE_CODE AND
NB.PLAN_PROD_FLAG = 'O' AND
NB.PLAN_PROD_GROUP = N.PLAN_PROD_GROUP  
LEFT JOIN output_prod_good_hc NC ON REPLACE(CONCAT(CAST(NA.PLAN_PROD_DATE AS CHAR),
CAST(NA.PLAN_PROD_LINE_CODE AS CHAR),
CAST(NA.PLAN_PROD_PART AS CHAR),
CAST(NA.PLAN_PROD_FLAG AS CHAR),
CAST(NA.PLAN_PROD_GROUP AS CHAR)),'-','') = NC.PLAN_ID
LEFT JOIN output_prod_good_hc ND ON REPLACE(CONCAT(CAST(NB.PLAN_PROD_DATE AS CHAR),
CAST(NB.PLAN_PROD_LINE_CODE AS CHAR),
CAST(NB.PLAN_PROD_PART AS CHAR),
CAST(NB.PLAN_PROD_FLAG AS CHAR),
CAST(NB.PLAN_PROD_GROUP AS CHAR)),'-','') = ND.PLAN_ID
LEFT JOIN toy_part N0 ON N.PLAN_PROD_PART = PART_NUM
LEFT JOIN line N1 ON N.PLAN_PROD_LINE_CODE= LINE_CODE 
WHERE 
REPLACE(CONCAT(CAST(NB.PLAN_PROD_DATE AS CHAR),
CAST(NB.PLAN_PROD_LINE_CODE AS CHAR),
CAST(NB.PLAN_PROD_PART AS CHAR),
CAST(NB.PLAN_PROD_FLAG AS CHAR),
CAST(NB.PLAN_PROD_GROUP AS CHAR)),'-','') = :idOt
ORDER BY  LINE_PREF, LINE_ORDR, N.PLAN_PROD_LINE_CODE, LINE_UNIT,  N.PLAN_PROD_GROUP`;
